apiVersion: apps/v1
kind: Deployment
metadata:
    name: webapp-deployment
spec:
    replicas: 3
    selector:
        matchLabels:
            app: webapp-pod
            version: v1
    template:
        metadata:
            name: webapp-pod
            labels:
                app: webapp-pod
                version: v1
        spec:
            containers:
            -  name: webapp
               image: manojvarma249/webapp:1.0
               imagePullPolicy: IfNotPresent
               ports:
                - containerPort: 8080
            imagePullSecrets:
             - name: dockerhub-cred
