apiVersion: apps/v1
kind: Deployment
metadata:
    name: webapp-deployment
spec:
    replicas: 3
    selector:
        matchLabels:
            app: webapp-pod
            version: v1
    strategy:
        type: RollingUpdate
    template:
        metadata:
            name: webapp-pod
            labels:
                app: webapp-pod
                version: v1
        spec:
            containers:
            -  name: webapp
               image: $DOCKER_IMAGE
               imagePullPolicy: Always
               ports:
                - containerPort: 8080
            imagePullSecrets:
             - name: dockerhub-cred
