apiVersion: v1
kind: Service
metadata:
    name: webapp-svc
    labels:
        app: webapp-deployment
spec:
    selector:
        app: Webapp-pod
        version: v1
    type: NodePort
    ports:
    - nodePort: 31000
      port: 80
      targetPort: 8080
